### ISSUE TITLE
Module not found: Error: Can't resolve 'jquery-asHoverScroll'

### ISSUE THREAD

**Issue by toniton** [amazingSurge/jquery-asHoverScroll#2]
I get this error when i try to inject jquery-asHoverScroll in angular2.

```
ERROR in ./src/app/main/login/login.component.ts
Module not found: Error: Can't resolve 'jquery-asHoverScroll' in '/Users/mac/Documents/Projects/nodejs/fixershub/src/app/main/login'
 @ ./src/app/main/login/login.component.ts 24:0-31
 @ ./src/app/main/login/login.module.ts
 @ ./src async
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4210 ./src/main.ts
```

**Comment by thecreation** [comment]
Did you 
```npm install jquery-asHoverScroll```

**Comment by toniton** [comment]
Yes I did, can't seem to figure out the exact problem but I created a new module and dumped your codes in one of the files and it fixed it for me. But all the other custom libraries worked fine.

**Comment by BryceBarbara** [comment]
Just to chime in, I'm also dealing with the same issue with a number of amazingSurge's modules. This one is the current problem though. Webpack can't find the module when I try to require it.

**Comment by thecreation** [comment]
Hi, we just releasse components as es module. It may fixed the issue.
