### ISSUE TITLE
package.json edit

### ISSUE THREAD

**Issue by unspokenn** [amazingSurge/jquery-asHoverScroll#3]
please add package.json to;
  "main": "dist/jquery-asHoverScroll.js",
  "module": "dist/jquery-asHoverScroll.es.js",

otherwise webpack building error occurs

![image](https://user-images.githubusercontent.com/3756497/32328150-2111a436-bfea-11e7-9daa-96e933e7ca77.png)

**Comment by snsxn** [comment]
@unspokenn you saved my day!

**Comment by thecreation** [comment]
Just release a new version. You can npm install without issues.
